# 운영 환경 Override
# 사용법: docker compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.prod up -d

services:
  mysql:
    container_name: wiki-mysql-prod
    restart: always

  app:
    container_name: wiki-app-prod
    restart: always

  influxdb:
    container_name: wiki-influxdb-prod
    restart: always

  prometheus:
    container_name: wiki-prometheus-prod
    restart: always

  mysql-exporter:
    container_name: wiki-mysql-exporter-prod
    restart: always

  loki:
    container_name: wiki-loki-prod
    restart: always

  promtail:
    container_name: wiki-promtail-prod
    restart: always

  grafana:
    container_name: wiki-grafana-prod
    restart: always
